### ISSUE TITLE
File not found when running aktemplates runserver

### ISSUE THREAD

**Issue by myicicle** [MoveOnOrg/actionkit-templates#17]
When I run aktemplates runserver, I get the following error on http://127.0.0.1:8000/:

No such file or directory: '/Library/Python/2.7/site-packages/actionkit_templates-0.1.1-py2.7.egg/actionkit_templates/contexts/event_places.csv'

![Screen Shot 2019-05-20 at 3 43 48 PM](https://user-images.githubusercontent.com/7129258/58047355-14cd3300-7b16-11e9-80b3-9a5013393d3e.png)

That file is indeed not in the package. Is it supposed to be?

**Comment by schuyler1d** [comment]
Hi @myicicle I think this is fixed by this PR
https://github.com/MoveOnOrg/actionkit-templates/pull/16

But I also think if you make sure to include the `-e` flag when you run:
`pip install -e git://github.com/MoveOnOrg/actionkit-templates#egg=actionkit-templates`
(possibly after uninstalling) then it's more likely to work as-is

**Comment by myicicle** [comment]
Thanks! Worked.
